### ISSUE TITLE
Legal Entity Setup

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#126]
### Goal
Setup legal entity for SecretDecks to have liability wrapper and steward-ownership of coop & its' assets.

### Specifications
Create legal documents reflecting our charter/mindfulness policy, how we work and vote, in order to establish UG in Germany with golden share veto model and steward-ownership.

### To Do's

- [ ] #128
- [x] #127
- [x] #11 
- [ ] Dividenden Anteile - Konzept (C-Anteile) [dividend shares - concept (C-shares)]
- [ ] Draft flow of voting tokens
- [ ] Research: Cap table on Cardano?

### Definition of Done
UG is setup and holding the secretdecks.com domain

## Further Information

![Screenshot 2021-10-15 at 23 00 49](https://user-images.githubusercontent.com/80257662/137553543-b4aafc09-1c28-4122-83b5-04f2e349680f.png)

Thoughts on setting up an Otoco LLC were voiced here #70 

[Here's the process document in German I filled out](https://docs.google.com/document/d/1qs_UwPeCoYl6naKiTpJCYNZjs5960asZ/edit?usp=sharing&ouid=111325662131461673184&rtpof=true&sd=true)

**Comment by DanM3rcurius** [comment]
**Salaries: highest salary can not be more than 5 times the lowest one**

**Comment by DanM3rcurius** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Governance-616fcf3d74c8bd0014baf6db/issues/SecretDecks/Documentation/126?planning-poker) with ZenHub @stephen-rowan
