### ISSUE TITLE
EPIC: How2? Intangible Contributions

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#55]
## **Goal** 
We want to track intangible contributions like care-work, ideas that are sparking projects, helping new members onboard, or just a witty comment to keep the energy up. 

## **Specifications** 
The contributions need to be aggregated, validated and in the end stored immutably as metadata on an NFT (more on that in in #61 )
Start small with an experimental approach: 5 different emojis each one having a different weight. Meaning one with more weight will generate more "Cred" the "currency" of SourceCred

Something along the lines of

[weight x1] "like" = Thumbsup emoji
[weight x2,5] "awesome" = Clap emoji
[weight x3] "love it" = Heart emoji
[weight x-1] "dislike" = Thumbsdown emoji
... ?

## Tasks
- [x] setup SourceCred instance on server from @tamagit80 for SecretDecks discord server
- [x] setup SourceCred instance on server from @tamagit80 for Catalyst discord server 
- [x] #76
- [x] design and create custom weights (@DanM3rcurius & @tamagit80)
- [x] experiment & test

## notes

- Ideally we can have custom emojis for the SourceCred reactions to better distinguish them from "normal" emojis that don't generate Cred
- from @wlstylr : We can add grain as metadata to the passport NFT and call the metadata slot "silo"

*Background* 
> @DanM3rcurius - Yes I think the original intention was for members to vote on other members "intangible" contributions - we will need to experiment on how this works out in practice I guess ? Other work that is categorized and have documented outputs are easier to confirm.

Yes! I was thinking sth along the lines of a short video, tweet, post that could reference or shortly describe the intangible work done. Example: <Thanks to (at)Stephen I now know where to find the material I'm looking for> ; or <(at)Dan took the time to introduce me to the project and answer many questions I had>.

Didn't you dabbled with SourceCred @stephen-rowan , what guide/tutorial did you use? I might look into setting this up. Maybe play around with it together with @wlstylr?

_Originally posted by @DanM3rcurius in https://github.com/SecretDecks/Documentation/issues/43#issuecomment-867475762_

**Comment by wlstylr** [comment]
I'm down to dabble with SourceCred a bit.  It looks like we can set it up on both Github and Discord.  Here is a link to the Discord setup instructions - https://sourcecred.io/docs/beta/plugins/discord

**Comment by stephen-rowan** [comment]
A bit tricky to setup - here is some notes I from when I was setting up ...

## Sourcecred example-instance Install on Ubuntu 20.04.2 LTS

## Error: The token supplied to $SOURCECRED_GITHUB_TOKEN doesn't match any format known to work.

1. Fresh Ubuntu image

2. Install yarn
``` shell
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn
```

2. Basic instructions - https://sourcecred.io/docs/setup/installation/

3. Clone sourcecred repo
``` shell
git clone https://github.com/sourcecred/example-instance.git
cd example-instance/
yarn
```

4. Clone a test repository
``` shell
git clone https://github.com/Ek-phrasis/HOLON-Sandbox.git
to /sourcecred/test/
```
5. Update sourcecred github plugin
``` shell
emacs config/plugins/sourcecred/github/config.json
added
("repositories": ["test/HOLON-Sandbox"]}
```
6. Edit  sourcecred.json
``` shell
emacs edit `sourcecred.json`
{ "bundledPlugins": ["sourcecred/discourse", "sourcecred/discord", "sourcecred/github"] }
```
to just include github  - 
``` shell
{ "bundledPlugins": ["sourcecred/github"] }
```

7. Load yarn 
``` shell 
yarn load
$ sourcecred load
GO   load
GO   loading sourcecred/github
Error: No GitHub token provided: set SOURCECRED_GITHUB_TOKEN
at getTokenFromEnv (webpack:///./src/plugins/github/plugin.js?:22:439)
at GithubPlugin.load (webpack:///./src/plugins/github/plugin.js?:22:894)
at loadCommand (webpack:///./src/cli/load.js?:6:1061)
DONE  load: 8ms
fatal: load failed for plugins: sourcecred/github
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
8. Check `.env` is present
``` shell
ls -a
example-instance/ .env is present at root of example-instance
```
9. Check `.env`  contains Token ID
``` shell
.env contains GitHub Token ID - Prefix - `SOURCECRED_GITHUB_TOKEN=
```
10 - set GitHub Token in environment : 
``` shell
export SOURCECRED_GITHUB_TOKEN="xyz"
Yarn load
yarn run v1.22.10
$ sourcecred load
GO   load
GO   loading sourcecred/github
Error: The token supplied to $SOURCECRED_GITHUB_TOKEN doesn't match any format known to work.
Please verify the token "" is correct, or report a bug if you think it should work.
    at validateToken (webpack:///./src/plugins/github/token.js?:15:476)
    at getTokenFromEnv (webpack:///./src/plugins/github/plugin.js?:22:579)
    at GithubPlugin.load (webpack:///./src/plugins/github/plugin.js?:22:894)
    at loadCommand (webpack:///./src/cli/load.js?:6:1061)
 DONE  load: 8ms
fatal: load failed for plugins: sourcecred/github
error Command failed with exit code 1.
```
11. ~~Should `.env` be at root of test repository ? try - `cp example-instance/.env example-instance/test/HOLON-Sandbox`~~

**Comment by stephen-rowan** [comment]
## Source Cred Server Setup Install on Ubuntu 20.04.2 LTS
![Screenshot from 2021-05-03 23-33-04](https://user-images.githubusercontent.com/25156451/116941665-0a0afa80-ac68-11eb-9cce-cb752ce494d0.png)

### Dependencies
Installed Node v14.4.0 (using nvm)
Yarn version : 1.22.10

``` shell
git clone https://github.com/sourcecred/sourcecred.git
cd sourcecred
yarn
yarn build
```

Then

```shell
yarn start
```
compiled with warnings

```shell
yarn run v1.22.10
$ ./scripts/devServer.sh
ℹ ｢wds｣: Project is running at http://localhost:8080/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/stephen/sourcecred
⚠ ｢wdm｣: Hash: 5d7e0bee738bdf1f6c29
Version: webpack 4.46.0
Time: 31668ms
Built at: 03/05/2021 23:24:25
                         Asset       Size  Chunks                         Chunk Names
           asset-manifest.json  304 bytes          [emitted]              
                   favicon.png   2.49 KiB          [emitted]              
                    index.html   3.11 KiB          [emitted]              
    static/js/main.cf9f57c2.js   9.05 MiB    main  [emitted] [immutable]  main
static/js/main.cf9f57c2.js.map   8.23 MiB    main  [emitted] [dev]        main
     static/js/ssr.0d8692be.js   9.25 MiB     ssr  [emitted] [immutable]  ssr
 static/js/ssr.0d8692be.js.map   8.47 MiB     ssr  [emitted] [dev]        ssr
       static/server-info.json   22 bytes          [emitted]              
Entrypoint main = static/js/main.cf9f57c2.js static/js/main.cf9f57c2.js.map
Entrypoint ssr = static/js/ssr.0d8692be.js static/js/ssr.0d8692be.js.map
[0] multi ./config/polyfills.js ./src/ui/index.js 40 bytes {main} [built]
[2] multi ./config/polyfills.js ./src/ui/server.js 40 bytes {ssr} [built]
[./config/polyfills.js] 785 bytes {main} {ssr} [built]
[./node_modules/@material-ui/core/esm/styles/index.js] 803 bytes {main} {ssr} [built]
[./node_modules/aphrodite/no-important.js] 51 bytes {ssr} [built]
[./node_modules/object-assign/index.js] 2.06 KiB {main} {ssr} [built]
[./node_modules/promise/lib/es6-extensions.js] 2.96 KiB {main} {ssr} [built]
[./node_modules/promise/lib/rejection-tracking.js] 2.81 KiB {main} {ssr} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} {ssr} [built]
[./node_modules/react-dom/server.browser.js] 228 bytes {ssr} [built]
[./node_modules/react-router-dom/esm/react-router-dom.js] 10.1 KiB {main} {ssr} [built]
[./node_modules/react-router/esm/react-router.js] 24.9 KiB {main} {ssr} [built]
[./node_modules/react/index.js] 190 bytes {main} {ssr} [built]
[./src/ui/index.js] 928 bytes {main} [built]
[./src/ui/server.js] 2.76 KiB {ssr} [built]
    + 1844 hidden modules

WARNING in ./src/util/getRandomValues.js 16:69-76
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./src/util/uuid.js
 @ ./src/ui/components/SpecialDistribution.js
 @ ./src/ui/components/AdminApp.js
 @ ./src/ui/index.js
 @ multi ./config/polyfills.js ./src/ui/index.js
ℹ ｢wdm｣: Compiled with warnings.
```

**Comment by stephen-rowan** [comment]
## Sourcecred example-instance Install on Ubuntu 20.04.2 LTS

## Error: The token supplied to $SOURCECRED_GITHUB_TOKEN doesn't match any format known to work.

1. Fresh Ubuntu image

2. Install yarn
``` shell
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn
```

2. Basic instructions - https://sourcecred.io/docs/setup/installation/

3. Clone sourcecred repo
``` shell
git clone https://github.com/sourcecred/example-instance.git
cd example-instance/
yarn
```

4. Clone a test repository
``` shell
git clone https://github.com/Ek-phrasis/HOLON-Sandbox.git
to /sourcecred/test/
```
5. Update sourcecred github plugin
``` shell
emacs config/plugins/sourcecred/github/config.json
added
("repositories": ["test/HOLON-Sandbox"]}
```
6. Edit  sourcecred.json
``` shell
emacs edit `sourcecred.json`
{ "bundledPlugins": ["sourcecred/discourse", "sourcecred/discord", "sourcecred/github"] }
```
to just include github  - 
``` shell
{ "bundledPlugins": ["sourcecred/github"] }
```

7. Load yarn 
``` shell 
yarn load
$ sourcecred load
GO   load
GO   loading sourcecred/github
Error: No GitHub token provided: set SOURCECRED_GITHUB_TOKEN
at getTokenFromEnv (webpack:///./src/plugins/github/plugin.js?:22:439)
at GithubPlugin.load (webpack:///./src/plugins/github/plugin.js?:22:894)
at loadCommand (webpack:///./src/cli/load.js?:6:1061)
DONE  load: 8ms
fatal: load failed for plugins: sourcecred/github
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
8. Check `.env` is present
``` shell
ls -a
example-instance/ .env is present at root of example-instance
```
9. Check `.env`  contains Token ID
``` shell
.env contains GitHub Token ID - Prefix - `SOURCECRED_GITHUB_TOKEN=
```
10 - set GitHub Token in environment : 
``` shell
export SOURCECRED_GITHUB_TOKEN="xyz"
Yarn load
yarn run v1.22.10
$ sourcecred load
GO   load
GO   loading sourcecred/github
Error: The token supplied to $SOURCECRED_GITHUB_TOKEN doesn't match any format known to work.
Please verify the token "" is correct, or report a bug if you think it should work.
    at validateToken (webpack:///./src/plugins/github/token.js?:15:476)
    at getTokenFromEnv (webpack:///./src/plugins/github/plugin.js?:22:579)
    at GithubPlugin.load (webpack:///./src/plugins/github/plugin.js?:22:894)
    at loadCommand (webpack:///./src/cli/load.js?:6:1061)
 DONE  load: 8ms
fatal: load failed for plugins: sourcecred/github
error Command failed with exit code 1.
```
11. ~~Should `.env` be at root of test repository ? try - `cp example-instance/.env example-instance/test/HOLON-Sandbox`~~

**Comment by DanM3rcurius** [comment]
Now I saw your documentation here @stephen-rowan Thank you!

**Goal** We want to track intangible contributions like care-work, ideas that are sparking projects, helping new members onboard, or just a witty comment to keep the energy up.

**Specifications** 5 different emojis each one having a different weight. Meaning one with more weight will generate more "Cred" the "currency" of SourceCred

Something along the lines of 
- [weight x1] "like" = Thumbsup emoji 
- [weight x2,5] "awesome" = Clap emoji
- [weight x3] "love it" = Heart emoji
- [weight x-1] "dislike" = Thumbsdown emoji

Ideally we can have custom emojis for the SourceCred reactions to better distinguish them from "normal" emojis that don't generate Cred

**Comment by DanM3rcurius** [comment]
How to validate and store data immutable?
https://github.com/SecretDecks/Documentation/issues/61#issuecomment-870398183

**Comment by DanM3rcurius** [comment]
Waiting for SourceCred bot setup @tamagit80 🙏🏿

**Comment by tamagit80** [comment]
yes im sorry but still getting same error, started again and created a rep
on SDgit ready to work as soon as i fix that stupid issue! :/ tomorrow
focus on that.

**Comment by DanM3rcurius** [comment]
I added role weight:
Default: 0 (so non members can't generate Can-D)
Shell: 1
Core: 2 (to incentivise becoming a core member)

I added all channels (hope that worked!)
💩 and 🤮 will now yield 0 Can-D
