### ISSUE TITLE
EPIC: Formalize Discord Voting Process 0.01

### ISSUE THREAD

**Issue by wlstylr** [SecretDecks/Documentation#61]
## Goal
Create process that describes how Discord voting will be initiated, executed, and recorded.  Use @stephen-rowan [comment](https://github.com/SecretDecks/Documentation/discussions/54#discussioncomment-918040) as a starting point.

## Specifications

- [x] 1. Flowchart of voting process
- [x] 2. Github .md file explaining in detail
- [x] 3. Discuss
- [x] 4. Create v 0.01
- [x] 5. Test vote
- [x] 6. Design Contribution Reward Mechanism Pilot

**Comment by DanM3rcurius** [comment]
Thanks for creating the Miro board @wlstylr ! I added some more content and also drafted sth like the beginning of a governance roadmap.

Here's the bigger picture:
<img width="1488" alt="Screenshot 2021-06-29 at 10 20 09" src="https://user-images.githubusercontent.com/80257662/123763111-c2999700-d8c3-11eb-91e3-fdef77d66614.png">

### Stage 1 Off Chain
1) SourceCred works as an aggregation layer for contribution data (tangible [github] and intangible [discord]) 
2) this contribution data can (should?) be validated by pools (until on chain gov and tokens are available this is to be done via discord polling of core members)
3) once verified the data is "charged" (as metadata) onto the members unique reputation NFT
4) Upon request of validation pools (or in set time intervals?) the reputation data is verified for merit, consistency or activity, or contested (review & appeal)
5) Voting is done via Validation pools

### Stage 1 On Chain
1) **Voting Token Faucet:** the reputation token (with the aggregated & verified reputation data) can request **binding** voting tokens, possible amount parameters: reputation value, -age; domain specific expertise allocated to Reputation Token; voting topic
2) On-Chain voting mechanism can be accessed to vote with acquired tokens; votes can be non-binding (loosely coupled) or binding (tightly coupled), respectively move from loose to tight
3) Optional: validation pools can verify voting and oversee token re-/distribution or burn [automate!]


💭 @stephen-rowan ?

**Comment by wlstylr** [comment]
![Screenshot 2021-06-29 7 39 15 PM](https://user-images.githubusercontent.com/58446163/123893745-d23fcc80-d911-11eb-8e48-f7c7fe5ba4ce.png)
I added a bit more to the governance roadmap outlining how the appeals process might look.  Thoughts?

**Comment by DanM3rcurius** [comment]
> ![Screenshot 2021-06-29 7 39 15 PM](https://user-images.githubusercontent.com/58446163/123893745-d23fcc80-d911-11eb-8e48-f7c7fe5ba4ce.png)
> I added a bit more to the governance roadmap outlining how the appeals process might look. Thoughts?

I agree with the additions. Only question: is it always the contributor appealing? Or can it also be another member?

**Comment by stephen-rowan** [comment]
How validation pools verify data seems a little opaque to me. What parameters verify the data ? Do you mean polls ?

**Comment by wlstylr** [comment]
> > ![Screenshot 2021-06-29 7 39 15 PM](https://user-images.githubusercontent.com/58446163/123893745-d23fcc80-d911-11eb-8e48-f7c7fe5ba4ce.png)
> > I added a bit more to the governance roadmap outlining how the appeals process might look. Thoughts?
> 
> I agree with the additions. Only question: is it always the contributor appealing? Or can it also be another member?

Good catch.  It can be another member and should read "Appeal survey prepared and submitted by contesting party"

**Comment by wlstylr** [comment]
> How validation pools verify data seems a little opaque to me. What parameters verify the data ? Do you mean polls ?

It's a little opaque for me as well, and I think we may not be able to bring clarity until we are actually in the process.  The objective of the validation pool (in my mind) is to verify that cred accumulated through Sourcecred is accurate and reconciled with contributions tracked through other sources such as the contribution survey.  This data would then been attributed to metadata on the reputation NFT as long as it was not appealed after the validation process.  Since we are a small team at the moment, I hope that we can come to non-contentious agreement quickly with simple polls during the validation process.

**Comment by DanM3rcurius** [comment]
Manually (via “soft protocols “) until we can start automating it for hard protocols.
Initial “Soft protocols” have to be established within first gov/stewardship Epoche.
I was thinking about using the term stewardship over governance. Think it has a better ring to it especially for creative/autonomous people.
Thoughts?

**Comment by DanM3rcurius** [comment]
PR #88 has the "Github .md file explaining in detail", for the time being - now and the first epoch until we have on chain voting & gov tokens ready.
I added it to "How to Contribute.md" in the root directory.
Voting v.01 is created (anon voting with pollmaster) and is currently being tested & voted upon.

**Comment by DanM3rcurius** [comment]
Pollmaster is successfully implemented and tested! Will close this issue now.
