### ISSUE TITLE
Fund 6 Proposal - Off2OnChain - Refinement

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#85]
# Summary
continuing from #81, this issue here is tracking the refinement of the proposal.
🔗  [Off2OnChain voting proposal link](https://cardano.ideascale.com/a/dtd/Off2On-Chain-self-governance-pilot/370236-48088#idea-tab-comments)🔗

### Checklist

- [x] Received emails from communications@iohk.io
- [x] Submitted this proposal to only one Challenge
- [x] Include identifying information about proposers
- [x] How my proposal impacts the challenge metrics
- [x] How I address the challenge question
- [x] Definition of success after 3, 6 and 12 months
- [x] Broken down my budget requirements
- [x] Defined expected launch date

TBD:
- [x] Budget breakdown
- [x] Milestone plan
- [x] Detailed execution
- [x] SecretDecks intro

### Who is SecretDecks ?

SecretDecks is a colourful collective of mindful spirits who work towards leaving this dimension a better place. Find out more about us on our "Arcana" GitBook at https://secretdecks.gitbook.io/arcana/introduction/who-and-what-is-secretdecks.

SecretDecks is building a Distributed Collective by discovering and exploring new tools for self organising communities. We share an agreed upon value system, defined in the Mindfulness Policy [link] that sets the base vibration of our work.

This pilot is driven within SecretDecks DisCo - DisCo stands for Distributed Collective. 

SecretDecks has a website at https://www.secretdecks.com/ , is developing an "Arcana" GitBook at https://secretdecks.gitbook.io/arcana/ . News and updates are posted on our Twitter at https://twitter.com/SecretDecks.

### Why is it a Problem?

Voting is possible when deciding which proposals should be funded through Project Catalyst, but there are no systems in place for the projects themselves that allow for voting on and recording operational decisions in a transparent and immutable way.

Subjective interpretation of past events can cause conflict and dissolution, which in turn can lead to organizational fragmentation.

### How does the solution addresses it?

A off2on chain voting mechanism will resolve conflict for self governing communities building on Cardano by creating an immutable record of agreed upon decisions. This system will provide a frame of reference that moves subjective arguments to objective consensus.

### How this meets the challenge question ?

By providing a frame of reference that moves subjective arguments to objective consensus we can encourage more meaningful participation in Project Catalyst from community members going forward.

### Relevant experience (identifying information)

Example -
**Stephen Whitenstall** has 30 years' experience in organizing academic, community and business projects. He develops, maintains documentation and provides technical project management support for Catalyst Swarm.

Include short bios here for ecah team member - highlight how their experience is relevant to this proposal

## Budget Breakdown

- UX design, wireframes - $ 700
- Code (Frontend Javascript or Vue,...?; - $ 950
- Message signer integration - $ 500
- Testing (what wallets?) - $ 290
-  Setup voting results simple web interface / vote NFT viewer: Approx. $ 300
- Documentation 20 hours per month at $ 40 hour for 3 months = $ 2400

**TOTAL: $ 5190**

### Milestone 0:  Dates ? - In Progress pre-funding
- basic tracking of contributions across different channels and spectrums (intangible & tangible) for more than two months; Setup SourceCred (to distribute social/community currency) and custom emoticons for Discord (**already done**).

### Milestone 1: Dates ? - November 2021 to ?
- First iteration (Simple Off2On-Chain voting)

### Milestone 2:  Dates ? - January 2022 to ?
- Second iteration (Good Off2On-Chain voting)

### General
- 1) SecretDecks quorum of at least 50%
### After 3 months
- 2) 1+ adoptions of  Simple SD Off2OnChain mechanism 
Completion of SD governance epoch without fragmentation of the organization
### After 6 months
- 3) 3+ adoptions of Good SD Off2OnChain
- 4) Completion of SD governance epoch without fragmentation of the organization

### First iteration (Simple Off2On-Chain voting)
simple discord voting, vote tallying in GitHub and peer approve, mint results as NFT; documentation
### Second iteration (Good Off2On-Chain voting)
voting with signing a tx (DCSPark) from wallet that is registered to member, voting power equals Cred, mint results as NFT; documentation

Current high level draft by @wlstylr 
![Screenshot 2021-09-02 at 11 53 20](https://user-images.githubusercontent.com/80257662/131823490-b8f6c167-1d44-444a-b2e9-0f7eff02b969.png)

## SecretDecks Introduction
![Screenshot 2021-09-07 at 01 52 32](https://user-images.githubusercontent.com/80257662/132266364-cacb7b6a-6105-4b9b-9cae-0c333c55b3f8.png)
from our [Arcana Gitbook](https://app.gitbook.com/@secretdecks/s/arcana/introduction/who-and-what-is-secretdecks9

**Comment by wlstylr** [comment]
> Budget Breakdown
minting of gov tokens: 5 ADA
distribution of gov tokens: 1,6 ADA * 10
minting of voting result NFTs: 40 ADA
Setup voting results simple web interface: apr. 200 ADA

@DanM3rcurius If voting power is determined by Can-d allocated through source cred, it may mean there would be multiple minting and distribution events for gov tokens as more were earned through SourcrCred.

**Comment by wlstylr** [comment]
I added the following to the proposal on IdeaScale:

> Although voting is possible when deciding which proposals should be funded through Project Catalyst, there is no system in place that allows for voting on and recording operational decisions in a transparent and immutable way. Subjective interpretation of past events causes conflict and dissolution, which in turn can lead to organizational fragmentation.
> A lean transparent immutable off to on-chain voting mechanism will help all Catalyst participants be more confident in the system, past events, and paths towards resolution when disagreements arise.

**Comment by DanM3rcurius** [comment]
> 
> @DanM3rcurius If voting power is determined by Can-d allocated through source cred, it may mean there would be multiple minting and distribution events for gov tokens as more were earned through SourcrCred.

Yes! Sharp observation Tyler 🙏
The budget would be for 1-2 months approximately. 

We could mint a very large number of gov/voting tokens and only distribute whenever minted (once a month or maybe only days b4 a voting event?)

**And/Or**

We keep the policy ID open for minting and  just keep minting another (large) nr of gov tokens

thoughts 💭?

**Comment by DanM3rcurius** [comment]
> I added the following to the proposal on IdeaScale:
> 
> > Although voting is possible when deciding which proposals should be funded through Project Catalyst, there is no system in place that allows for voting on and recording operational decisions in a transparent and immutable way. Subjective interpretation of past events causes conflict and dissolution, which in turn can lead to organizational fragmentation.
> > A lean transparent immutable off to on-chain voting mechanism will help all Catalyst participants be more confident in the system, past events, and paths towards resolution when disagreements arise.

Amazing! Thanks Tyler 🙏
I’ll add SD info today!

**Comment by wlstylr** [comment]
## KPIs

- SecretDecks quorum of at least 50%
- 1+ adoptions of SD Off2OnChain mechanism
- Completion of SD governance epoch without fragmentation of the organization

**Comment by DanM3rcurius** [comment]
add budget for on chain voting UX design and code?

cred to gov exchange rate?

mention collab with @stephen-rowan ?

### Epic Milestones
- simple discord voting, vote talling in github and signup, mint results as nft
- voting with signing tx (DCSPark) from wallet that is registered to member, vote weight looked up in SourceCred

**Comment by stephen-rowan** [comment]
## Describe your solution to the problem 
"An open source & lean off2on chain voting mechanism for self governing communities building on Cardano."
https://cardano.ideascale.com/a/dtd/Off2On-Chain-self-governance-pilot/370236-48088

This solution does not mention how it resolves conflict resolution (as per problem statement). I would include a reference to how this resolves conflict resolution in the solution.
Something like ...
"A off2on chain voting mechanism will resolve conflict for self governing communities building on Cardano by ... [example]"

**Comment by DanM3rcurius** [comment]
pilot r & d can we correlate minting native cardano or our gov tokens with grain?

**Comment by stephen-rowan** [comment]
Rewrite - 

Voting is possible when deciding which proposals should be funded through Project Catalyst, but there are no systems in place for the projects themselves that allow for voting on and recording operational decisions in a transparent and immutable way. 

Subjective interpretation of past events can cause conflict and dissolution, which in turn can lead to organizational fragmentation.

A lean transparent immutable off to on-chain voting mechanism will help participants be more confident in the organisation of their project’s systems, awareness of past events, and provide paths towards resolution when disagreements arise.

**Comment by wlstylr** [comment]
> ## Describe your solution to the problem
> "An open source & lean off2on chain voting mechanism for self governing communities building on Cardano."
> https://cardano.ideascale.com/a/dtd/Off2On-Chain-self-governance-pilot/370236-48088
> 
> This solution does not mention how it resolves conflict resolution (as per problem statement). I would include a reference to how this resolves conflict resolution in the solution.
> Something like ...
> "A off2on chain voting mechanism will resolve conflict for self governing communities building on Cardano by ... [example]"

A off2on chain voting mechanism will resolve conflict for self governing communities building on Cardano by creating an immutable record of agreed upon decisions.  This system will provide a frame of reference that moves subjective arguments to objective consensus.

**Comment by DanM3rcurius** [comment]
> A off2on chain voting mechanism will resolve conflict for self governing communities building on Cardano by creating an immutable record of agreed upon decisions. This system will provide a frame of reference that moves subjective arguments to objective consensus.

genius!

**Comment by stephen-rowan** [comment]
> 
> 
> add budget for on chain voting
> 
>     * UX design, wireframes (600€)
> 
>     * code (Frontend Javascript or Vue,...?;  (800€)
> 
>     * message signer integration (400€)
> 
>     * testing (what wallets?) (200€)
> 
> 
> ### TBD
> 
> -cred to gov exchange rate?
> 
>     * mention collab with @stephen-rowan ?
> 
> 
> ### Epic Milestones
> 
>     * simple discord voting, vote talling in github and signup, mint results as nft
> 
>     * voting with signing tx (DCSPark) from wallet that is registered to member, vote weight looked up in SourceCred

## Budget for Documentation / Tracking
- If SD want to communicate a solution as well 
- 20 hours per month at $ 40 hour for 3 months  = $ 2400 - (based on time I spend tracking Swarm applied to communal SD effort).
- Documentation should be added to the Milestone plan

**Comment by stephen-rowan** [comment]
### Overview 
This pilot is driven within SecretDecks DisCo - DisCo stands for Distributed Collective. SecretDecks is building a Distributed Collective by [ ....]
### Relevant Experience (identifying information about proposers)
Team bios here
### Detailed Solution
SecretDecks aim to introduce a tightly coupled on-chain voting system by minting voting tokens and distributing them based upon a SourceCred cross-reference.
SourceCred  is [explanation]
The structure of the process will be a binary Yes/No decision option.
These Yes/No decisions will be mapped to individual wallet addresses.
etc ...
### How this meets the challenge question ?
By providing a frame of reference that moves subjective arguments to objective consensus we can encourage more meaningful participation in Project Catalyst from community members going forward,

**Comment by stephen-rowan** [comment]
Hi Dan,Tyler,  I have edited the main body with changes for the proposal. Will check in later. 
The main thing to remember is that CAs will not know who we are - so we have to explain everything to them (as briefly as possible). To make it easy for CAs we should signpost what they need for assessments (e.g. the checklist).
All the best S

**Comment by DanM3rcurius** [comment]
[proposal link](https://cardano.ideascale.com/a/dtd/Off-to-On-Chain-Self-Governance/370236-48088)
thanks @stephen-rowan and @wlstylr for your work on this!
